### ISSUE TITLE
Can you show screenshots?

### ISSUE THREAD

**Issue by snxox** [Heisenberg976/Google-Keep-Clone#2]
I want to show my friends this code and I want to share it 😁 
Can you show me some screenshots? 
Thank you 🙏

**Comment by Heisenberg976** [comment]
You can just give them link and let.them see my code on github

**Comment by NikaMikeltadze** [comment]
screenshots of the project?

**Comment by snxox** [comment]
Yess

**Comment by NikaMikeltadze** [comment]
![login](https://user-images.githubusercontent.com/77876435/133474750-c3c1e6c3-34b2-4b2e-9cb1-412576fa8536.png)
![image](https://user-images.githubusercontent.com/77876435/133475092-76921227-ad2b-400a-83a7-458e7c389669.png)
![image](https://user-images.githubusercontent.com/77876435/133475137-bdb8e604-313e-4b2d-89f4-5dbf21bf501c.png)
![image](https://user-images.githubusercontent.com/77876435/133475183-ffe38549-183d-406f-b2ee-77cf8c0378c3.png)
![image](https://user-images.githubusercontent.com/77876435/133475238-ed85888f-a0bc-4f0b-9f4d-cf329c12ffdb.png)
![image](https://user-images.githubusercontent.com/77876435/133475295-a3270024-ea4e-431b-b0d5-8d1d4b4cd67f.png)

Design is not very good but, everything is fully functional

**Comment by snxox** [comment]
Can you create a beautiful UI like Google Keep? only same ui? Then I will promote this project for free
